name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build and Commit to docs"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

# 同時デプロイを抑止（新しい実行が来たら古い方を自動キャンセル）
concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  deploy:
    # Build が成功かつ main ブランチのときだけ実行
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'  # deploy.yml でコミットされたビルド成果物

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
